name: Build and Publish bitcoind CSFS Image

on:
  workflow_dispatch:
    inputs:
      commit:
        description: Git ref/commit or branch to build (e.g., 2025-04-csfs)
        required: true
        default: 2025-04-csfs
      bitcoin_repo:
        description: Bitcoin repository URL to build from
        required: true
        default: https://github.com/jamesob/bitcoin.git
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      COMMIT: ${{ inputs.commit || '2025-04-csfs' }}
      BITCOIN_REPO: ${{ inputs.bitcoin_repo || 'https://github.com/jamesob/bitcoin.git' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./bitcoind-tests
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            COMMIT=${{ env.COMMIT }}
            BITCOIN_REPO=${{ env.BITCOIN_REPO }}
          tags: |
            ghcr.io/starkware-bitcoin/markstr-bitcoind:${{ env.COMMIT }}
            ghcr.io/starkware-bitcoin/markstr-bitcoind:latest